### ISSUE TITLE
intro or about

### ISSUE THREAD

**Issue by jaseem1999** [gazijarin/gazi#4]
**_SideBarNav.js file_**
const links = [
      <a href="**#**">/home</a>, your home a link is empty. a href="#" ,home
      <a href="#about">/about</a>,
      <a href="#experience">/experience</a>,
      <a href="#projects">/software-creations</a>
    ]

Your SlideBarNav.js is <a herf="#">/home</a>is empty. 
+add <a href="#intro">/home</a>, a href="#intro",home
SlideBarNav.js file attached https://github.com/gazijarin/Gazi/blob/main/src/components/SidebarNav.js
the problem issues line number 32

**Comment by jaseem1999** [comment]
awesome..:) website

**Comment by gazijarin** [comment]
Should be fixed with the new update!
